{% set name = "numpyro" %}
{% set version = "0.13.2" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 526f0b15518094c78e68df6e330c9c1c9cea1274dac69f05617224fa6d954ee8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - jax >=0.2
    - jaxlib >=0.1.55
    - multipledispatch
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
