{% set name = "numpyro" %}
{% set version = "0.15.2" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e86dd3ac3c90e4ddaebb32f3cc4bacd5ccc2b6f837334c01a2b2e8daf419a331

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - jax >=0.4.14
    - jaxlib >=0.4.14
    - multipledispatch
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
