{% set name = "numpyro" %}
{% set version = "0.16.1" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 553ea56c729bdeb83d6eb6d455911113dc75f5eb25a59e3af31a7726313eee38

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - jax >=0.4.14
    - jaxlib >=0.4.14
    - multipledispatch
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
