{% set name = "numpyro" %}
{% set version = "0.20.0" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cebd0f313866eb0157e3153a9bf56f211020aa07f6a0104a4c36c483496f97b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - jax >=0.4.14
    - jaxlib >=0.4.14
    - multipledispatch
    - numpy
    - python >={{ python_min }}
    - tqdm
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
