{% set name = "numpyro" %}
{% set version = "0.18.0" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9799abeb801f940b8257a7dcfab0542a2a527e0f27c34e7fc57e7c30dd113527

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - jax >=0.4.14
    - jaxlib >=0.4.14
    - multipledispatch
    - numpy
    - python >={{ python_min }}
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
