{% set name = "numpyro" %}
{% set version = "0.13.0" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fee4ae9f6656ad2a45c6571cca7158663f95cdb8979e33e19c089d4a87f58c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - jax >=0.2
    - jaxlib >=0.1.55
    - multipledispatch
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
