{% set name = "numpyro" %}
{% set version = "0.13.1" %}

package:
  name: numpyro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fee70d735ab5331714c392e1e0a0615d21df6e0b22bb2ed2eeba40b437a2943

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - jax >=0.2
    - jaxlib >=0.1.55
    - multipledispatch
    - numpy
    - python >=3.6
    - tqdm

test:
  imports:
    - numpyro

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
